apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: todonodejs
    name: route-frontend
  name: frontend
spec:
  host: todo.apps.uno.danielsdemo.de
  path: "/todo"
  to:
    kind: Service
    name: frontend
    weight: 100
  wildcardPolicy: None
